### ISSUE TITLE
自定义探测结果 无法更新到instanceLocalValue

### ISSUE THREAD

**Issue by davionchen** [polarismesh/polaris-java#33]
**Describe the bug**
自定义探测结果 无法更新到instanceLocalValue
**To Reproduce**

![image](https://user-images.githubusercontent.com/2884774/144784284-6ed4c288-089b-476a-ab89-16017a2d5031.png)

自定义探测结果返回类型为：OutlierDetectionStatus，但是InstanceLocalValue的方法为setDetectResult(DetectResult result)
类型不一致性，更新失败

**Expected behavior**

**Environment**
- Version: [1.2.2-SNAPSHOT]

**Additional context**

**Comment by davionchen** [comment]
补充一点：

调整buildInstanceUpdateResult的组装逻辑。

```java
  properties.put(PROPERTY_DETECT_RESULT,entry.getValue());
//     new OutlierDetectionStatus(entry.getValue().getDetectType(), OutlierDetectionStatus.Status.HEALTHY,
//     entry.getValue().getLastDetectTime().getTime()));
```


使用如下配置：
```yaml
consumer:

  outlierDetection:

    enable: true
    checkPeriod: 10000
    when: on_recover
```

一旦触发了探测，探测机制无法停止下来。
